/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sinking_ships.controller;

import org.junit.jupiter.api.Test;

import sinking_ships.view.MainView;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appExists() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should be a class");
    }
}
