/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sinking_ships.controller;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appExists() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should be a class");
    }

    @Test
    public void shouldBeAbleToCallCreatePlayer() {
        App app = new App();
        assertNotNull(app.createPlayer(), "should be able to create player");
    }

    @Test
    public void shouldReturnPlayer() {
        App app = new App();
        Player actual = app.createPlayer();
        assertTrue(actual instanceof Player);
    }
}
