/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package sinkingships.controller;

/**
 * App class main starting point for the application.
 */
public class App {

  // public static void main(String[] args) {

  // }
}
