/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package sinkingships.controller;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

/**
 * Unit test for the App class.
 */
class AppTest {
  @Test
  void appExists() {
    App sut = new App();
    assertNotNull(sut, "app should be a class");
  }
}
